require:
  - rubocop-minitest
  - rubocop-performance

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.6
  Exclude:
    - "tmp/**/*"
    - "vendor/**/*"

Layout/LineLength:
  Exclude:
    - "*.gemspec"
    - "test/**/*"

Metrics/AbcSize:
  Max: 16
  Exclude:
    - "test/**/*"

Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
    - "Rakefile"
    - "bin/lazylead"
    - "test/lazylead/cli/start_test.rb"

Metrics/ClassLength:
  Exclude:
    - "test/**/*"

Metrics/MethodLength:
  Max: 15
  Exclude:
    - "test/**/*"

Metrics/ParameterLists:
  Max: 3

Layout/HashAlignment:
  EnforcedColonStyle:
    - table
    - key
  EnforcedHashRocketStyle:
    - table
    - key

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrivialAccessors:
  AllowPredicates: true

Style/EndOfLine:
  EnforcedStyle: lf

# @todo #/DEV Add violation regarding methods without documentation using RDoc
#  https://stackoverflow.com/questions/1681467/how-to-document-ruby-code
