architect:
  - dgroup
assets:
  rubygems.yml: dgroup/ossrh#rubygems.yml
  circleci.token: dgroup/ossrh#circleci.token
install: |
  export GEM_HOME=~/.ruby
  export GEM_PATH=$GEM_HOME:$GEM_PATH
docker:
  image: ruby:2.6.5
release:
  script: |-
    export RUBYOPT="-W0"
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    sed -i "s/0\.0\.0/${tag}/g" lib/lazylead/version.rb
    sed -i "s/0\.0\.0/${tag}/g" lazylead.gemspec
    bundle install --no-color
    bundle exec rake test rubocop sqlint xcop
    git add lib/lazylead/version.rb lazylead.gemspec
    gem build lazylead.gemspec
    chmod 0600 ../rubygems.yml
    # gem push *.gem --config-file ../rubygems.yml
    export token=$(< ../circleci.token)
    curl -X POST --url https://circleci.com/api/v2/project/gh/dgroup/lazylead/envvar?circle-token=$token -H "accept: application/json" -H "content-type: application/json" -d "{ \"name\": \"DOCKER_RELEASE_TAGS\", \"value\": \"latest ${tag}\" }"
    exit -2
merge:
  script: |-
    bundle install
    bundle exec rake test rubocop sqlint xcop
