architect:
  - dgroup
assets:
  rubygems.yml: dgroup/ossrh#rubygems.yml
  circleci.token: dgroup/ossrh#circleci.token
install: |
  export GEM_HOME=~/.ruby
  export GEM_PATH=$GEM_HOME:$GEM_PATH
  sudo apt-get -y update
  sudo apt-get -y install libcurl4-openssl-dev
  sudo gem install pdd -v 0.20.5
release:
  script: |-
    export RUBYOPT="-W0"
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
#    sed -i "s/0\.0\.0/${tag}/g" lib/lazylead/version.rb
#    bundle install --no-color
#    rake --quiet
#    git add lib/lazylead/version.rb
#    git commit -m "version set to ${tag}"
#    gem build lazylead.gemspec
#    chmod 0600 ../rubygems.yml
#    gem push *.gem --config-file ../rubygems.yml
    echo "Set docker release tags on CI"
    curl --request POST \
      --url https://circleci.com/api/v2/project/gh/dgroup/lazylead/envvar \
      --header 'accept: application/json' \
      --header 'circle-token: $(cat ${circleci.token)' \
      --header 'content-type: application/json' \
      --data '{
      "name": "DOCKER_RELEASE_TAGS",
      "value": "latest ${tag}"
    }'
merge:
  script: |-
    bundle install
    rake --quiet
    pdd -f /dev/null -v
