architect:
  - dgroup
assets:
  rubygems.yml: dgroup/ossrh#rubygems.yml
  circleci.token: dgroup/ossrh#circleci.token
docker:
  image: ruby:2.6.5
release:
  script: |-
    export RUBYOPT="-W0"
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    sed -i "s/0\.0\.0/${tag}/g" lib/lazylead/version.rb
    sed -i "s/0\.0\.0/${tag}/g" lazylead.gemspec
    # bundle install --no-color
    # rake --quiet
    # git add lib/lazylead/version.rb lazylead.gemspec
    # gem build lazylead.gemspec
    curl -X POST --url https://circleci.com/api/v2/project/gh/dgroup/lazylead/envvar -H 'accept: application/json' -H 'circle-token: $(cat ../circleci.token)' -H 'content-type: application/json' -d '{ "name": "DOCKER_RELEASE_TAGS", "value": "latest ${tag}" }'
    exit -2
merge:
  script: |-
    bundle install
    rake --quiet
