version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      # build the application image
      - run: |
          set -e
          docker build --build-arg release_tags="${CIRCLE_SHA1}, ${CIRCLE_BRANCH}, ${CIRCLE_COMPARE_URL}" \
            -t dgroup/lazylead:$CIRCLE_BRANCH .
          docker run --rm dgroup/lazylead bin/lazylead --verbose --trace > trace.log
          cat trace.log
          grep --color -n "No tasks found" trace.log

      # publish the image
      - run: |
          docker login --username $DOCKER_USER --password $DOCKER_TOKEN
          docker push dgroup/lazylead:$CIRCLE_BRANCH
