version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      # build the application image
      - run: |
          set -e
          COMMIT_URL="https://github.com/dgroup/rll/commit/${CIRCLE_SHA1}"
          docker build --build-arg release_tags="${CIRCLE_SHA1}, ${CIRCLE_BRANCH}, ${COMMIT_URL}" \
            -t dgroup/lazylead:$CIRCLE_BRANCH . \
            -f .docker/Dockerfile
          docker run --rm dgroup/lazylead:${CIRCLE_BRANCH} bin/lazylead --verbose > trace.log
          cat trace.log
          grep --color "No taskssssss found" trace.log

      # publish the image
      - run: |
          docker login --username $DOCKER_USER --password $DOCKER_TOKEN
          docker push dgroup/lazylead:$CIRCLE_BRANCH
