# @todo #/DEV Define automatic integration between rultor and Circle CI.
#  Right not its not clear how to automatically accept the merge requests into master.
#  Without this integration the release history won't be clear.
version: 2
jobs:
  test:
    docker:
      - image: ruby:2.6.5-alpine
    steps:
      - checkout
      - run: |
          apk add libc-dev gcc make git sqlite sqlite-dev sqlite-libs
          bundler install
      - run: bundle exec rake test rubocop sqlint xcop
  deploy:
    machine: true
    steps:
      - checkout
      # build the application image
      - run:
          name: "Build docker image"
          command: |
            set -e
            COMMIT_URL="https://github.com/dgroup/lazylead/commit/${CIRCLE_SHA1}"
            docker build --build-arg release_tags="${CIRCLE_SHA1}, ${CIRCLE_BRANCH}, ${COMMIT_URL}" --build-arg version="${DOCKER_RELEASE_TAGS:7}" \
              -t dgroup/lazylead:$CIRCLE_BRANCH . \
              -f .docker/Dockerfile
            echo "Available LL images:"
            docker images | grep lazylead
            docker run --rm dgroup/lazylead:${CIRCLE_BRANCH} bin/lazylead --verbose > trace.log
            cat trace.log
            expected="No tasks found"
            echo "Ensure that app prints the line '${expected}'."
            grep --color "${expected}" trace.log
      # publish the image
      - run:
          name: "Deploy docker image"
          command: |
            chmod +x .circleci/release_image.sh
            .circleci/release_image.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - test
