version: '2.3'

# @todo #/DEV Define openshift template in order to deploy into Openshift/Kubernetes/etcN environment.
services:

  lazylead:
    image: dgroup/lazylead:latest
    container_name: lazylead
    mem_limit: 128m
    build:
      context: ../
      dockerfile: .docker/Dockerfile
      args:
        release_tags: "latest 0.1.0"
        version: "0.1.0"
    ports:
      - 82:8080
      - 1082:1082 # remote debug
      - 1282:1282 # JMX connection for jvisualvm debug
    volumes:
      - .local/dumps:/lazylead/dumps
      - .local/logs:/lazylead/logs
    entrypoint: bin/lazylead --trace --verbose --log-file /lazylead/logs/ll{{.%Y-%m-%dT%H:%M:%S}}.log
